name: 'Terraform'
 
on: [push, pull_request]
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v3.0.0
      with:
        go-version: 1.17
 
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.7

    - name: Azure Login
      uses: Azure/login@v1.4.4
      with:
        creds: '{"clientId": "${{ secrets. AZURE_AD_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_AD_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.AZURE_AD_TENANT_ID }}", "resourceManagementEndpointUrl": "https://management.azure.com"}'

    - name: Run build script
      run: go run main.go
 
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -input=false
      working-directory: "./terraform"