name: 'Terraform'
 
on: [push, pull_request]
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VAR_deployment_name: ${{ secrets.DEPLOYMENT_NAME }}
      TF_VAR_location: ${{ secrets.LOCATION }}
      TF_VAR_registry_name: ${{ secrets.REGISTRY_NAME }}
      TF_VAR_registry_rg: ${{ secrets.REGISTRY_RG }}
      TF_VAR_container_image_url: ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.CONTAINER_REPOSITORY }}
      TF_VAR_container_image_tag: ${{ secrets.CONTAINER_TAG }}
      TF_VAR_terraform_backend_resource_group: ${{ secrets.TERRAFORM_BACKEND_RESOURCE_GROUP }}
      TF_VAR_terraform_backend_storage_account: ${{ secrets.TERRAFORM_BACKEND_STORAGE_ACCOUNT }}
      NODE_NAME: ${{ secrets.DEPLOYMENT_NAME }}.${{ secrets.LOCATION }}.azurecontainer.io
    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: "./terraform"
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Replace tokens
      # You may pin to the exact commit or the version.
      # uses: cschleiden/replace-tokens@4f7e3d67f3ff2317ae650842145cdbaefba65189
      uses: cschleiden/replace-tokens@v1.1
      with:
        tokenPrefix: __
        tokenSuffix: __
        files: app/config/teleport.yaml   
  
    - name: ACR Build
      id: acr
      uses: azure/acr-build@v1
      with:
        git_access_token: ${{ secrets.GITHUB_TOKEN }}
        service_principal: ${{ secrets.AZURE_AD_CLIENT_ID }}
        service_principal_password: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        tenant: ${{ secrets.AZURE_AD_TENANT_ID }}
        registry: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        repository: ${{ secrets.CONTAINER_REPOSITORY }}
        tag: ${{ secrets.CONTAINER_TAG }}
        branch: main
 
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.7

    - name: 'Terraform Format'
      run: terraform fmt -check
         
    - name: 'Terraform Init'
      run: terraform init
 
    - name: 'Terraform Validate'
      run: terraform validate -no-color
         
    - name: 'Terraform Plan'
      run: terraform plan
 
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -input=false